{% set version = "0.4.0" %}

package:
  name: phreeqpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/phreeqpy/phreeqpy-{{ version }}.tar.gz
  sha256: 31b21b9eb18af0d1d53b99555e7199cba44fd5159c8e20c0a8711f45cb55ed19

build:
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - phreeqpy
    - phreeqpy.iphreeqc

about:
  home: http://www.phreeqpy.com/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python tools for PHREEQC

extra:
  recipe-maintainers:
    - ocefpaf
